### ISSUE TITLE
UIHelper.startVerificationUsingFacebookToken unknow method

### ISSUE THREAD

**Issue by felixeduardo15** [Lenddo/android-lenddo-data#19]
After import a new version of LenddoSDK this method cannot resolve.

it change?

import com.lenddo.sdk.utils.UIHelper;

**Comment by Howard3** [comment]
@felixeduardo15 thanks for the report, can you please provide more information, perhaps some sample code with regards to the integration? Thanks!

**Comment by felixeduardo15** [comment]
`UIHelper.startVerificationUsingFacebookToken($this.getActivity(), facebookToken, expiration, $this.helper);`

after update lenddoSDK this method show the error Cannot resolve method. @Howard3

**Comment by jom16antonio** [comment]
For Lenddo Onboarding SDK please use : https://github.com/Lenddo/android-lenddo-onboarding
For Lenddo Data SDK please use : https://github.com/Lenddo/android-lenddo-data

**Comment by felixeduardo15** [comment]
Already update both, but, the error continues. @jom16antonio

**Comment by jom16antonio** [comment]
The method was removed when the SDK was upgraded to Authorize-v3 last Feb 2017. 
We will be working on how to get back support for this. We will get back to you as soon as there is an update.

**Comment by jom16antonio** [comment]
@felixeduardo15,
Since you are also using the Lenddo Data SDK please use that to pass the FB access token.
To do this:
1. Use the DATASDK and follow the instructions in Passing the Provider Access Token guide.
https://github.com/Lenddo/android-lenddo-data#user-content-passing-the-provider-access-token
2. Also, please follow the guide in Sending Application Data. This is where you will pass your verification data. Just copy paste the code snippet and apply available data as per the example.
https://github.com/Lenddo/android-lenddo-data#user-content-sending-application-data

**Comment by Howard3** [comment]
@felixeduardo15 I wanted to follow up to determine if you're still having issues or if we may close this ticket.
