### ISSUE TITLE
app:transformClassesWithJarMergingForDebug

### ISSUE THREAD

**Issue by gustavomc** [Lenddo/android-lenddo-data#2]
Error:Execution failed for task ':app:transformClassesWithJarMergingForDebug'.

> com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: com/lenddo/okhttp/internal/tls/OkHostnameVerifier.class

error when i try to run.

i have added both lenddodatasdk and LendooSDK.

why this happens?

**Comment by jom16antonio** [comment]
Hi,

It seems you are using both the Lenddo Data SDK and the Lenddo Onboarding SDK in a single application. While this is not yet "officially" supported, it is possible to proceed by using this hack.

First, please try to update the Lenddo Onboarding SDK to the latest commited release.

Then, In your Lenddo Onboarding SDK build.gradle file, kindly change the dependency from:

``` xml
dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile "com.google.code.gson:gson:2.7"
    compile 'com.squareup.mimecraft:mimecraft:1.1.1'
    compile 'commons-codec:commons-codec:1.10'
    compile 'org.apache.commons:commons-lang3:3.4'
    compile 'com.android.support:support-v4:24.1.1'
}
```

to:

``` xml
dependencies {
//    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile "com.google.code.gson:gson:2.7"
    compile 'com.squareup.mimecraft:mimecraft:1.1.1'
    compile 'commons-codec:commons-codec:1.10'
    compile 'org.apache.commons:commons-lang3:3.4'
    compile 'com.android.support:support-v4:24.1.1'
    compile project(':lenddodatasdk')
}
```

This fix will make use of the jar files in the lenddodatasdk modules instead of the jar files included in the onboarding sdk. They are basically the same files, but since they are duplicates. It will cause an issue.

**Comment by gustavomc** [comment]
thanks this solved my issue
